# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flash_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setEnabled(False)
        mainWindow.resize(764, 353)
        mainWindow.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dropshawdowframe = QtWidgets.QFrame(self.centralwidget)
        self.dropshawdowframe.setStyleSheet("QFrame{\n"
"Background-color:#295C82;\n"
"color: rgb(220, 220, 220);\n"
"Border-radius: 10px;\n"
"}")
        self.dropshawdowframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropshawdowframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropshawdowframe.setObjectName("dropshawdowframe")
        self.lbNameApp = QtWidgets.QLabel(self.dropshawdowframe)
        self.lbNameApp.setGeometry(QtCore.QRect(40, 40, 671, 71))
        font = QtGui.QFont()
        font.setFamily("UTM Androgyne")
        font.setPointSize(40)
        self.lbNameApp.setFont(font)
        self.lbNameApp.setStyleSheet("color:#4A94E9")
        self.lbNameApp.setAlignment(QtCore.Qt.AlignCenter)
        self.lbNameApp.setObjectName("lbNameApp")
        self.description = QtWidgets.QLabel(self.dropshawdowframe)
        self.description.setGeometry(QtCore.QRect(290, 120, 351, 51))
        font = QtGui.QFont()
        font.setFamily("UTM Androgyne")
        font.setPointSize(15)
        self.description.setFont(font)
        self.description.setStyleSheet("\n"
"color:#83C3FF;")
        self.description.setAlignment(QtCore.Qt.AlignCenter)
        self.description.setObjectName("description")
        self.progressBar = QtWidgets.QProgressBar(self.dropshawdowframe)
        self.progressBar.setGeometry(QtCore.QRect(120, 210, 541, 21))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"background-color:#A9D6E4;\n"
"color:#FFFFFF;\n"
"border-style:none;\n"
"border-radius:10;\n"
"text-align:center;\n"
"}\n"
"QProgressBar::chunk{\n"
"border-radius:10;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.00568182 rgba(36, 131, 227, 255), stop:0.931818 rgba(113, 219, 255, 255));\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.loading = QtWidgets.QLabel(self.dropshawdowframe)
        self.loading.setGeometry(QtCore.QRect(280, 240, 221, 21))
        font = QtGui.QFont()
        font.setFamily("UTM Androgyne")
        font.setPointSize(10)
        self.loading.setFont(font)
        self.loading.setStyleSheet("\n"
"color:#83C3FF;")
        self.loading.setAlignment(QtCore.Qt.AlignCenter)
        self.loading.setObjectName("loading")
        self.create = QtWidgets.QLabel(self.dropshawdowframe)
        self.create.setGeometry(QtCore.QRect(530, 300, 221, 21))
        font = QtGui.QFont()
        font.setFamily("UTM Androgyne")
        font.setPointSize(10)
        self.create.setFont(font)
        self.create.setStyleSheet("\n"
"color:#83C3FF;")
        self.create.setAlignment(QtCore.Qt.AlignCenter)
        self.create.setObjectName("create")
        self.verticalLayout.addWidget(self.dropshawdowframe)
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "simple filter "))
        self.lbNameApp.setText(_translate("mainWindow", "<Strong> SIMPLE FILTER </Strong> APP"))
        self.description.setText(_translate("mainWindow", "Together create unique photos\n"
""))
        self.loading.setText(_translate("mainWindow", "loading..."))
        self.create.setText(_translate("mainWindow", "<strong>Created by</strong>: TUT team"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
